name: puntorojo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  url_launcher: ^6.2.6
  youtube_player_flutter: ^9.1.1
  font_awesome_flutter: ^10.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.4.1
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  flutter_animate: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/coopinga.png
    - assets/images/puntorojo4.jpg
    - assets/images/puntorojo2.jpg
    - assets/images/puntorojo3.png
    - assets/images/puntorojo.jpg
